const SOURCE_REGISTRY = [
    // ===== GLOBAL / WIRES =====
    {
        id: "reuters",
        name: "Reuters",
        matchers: ["reuters.com"],
        country: "United Kingdom",
        region: "Europe",
        tier: "top",
        influenceWeight: 1.45,
        reliabilityScore: 0.95,
        focus: "international",
        sourceType: "wire",
        language: "en",
        coverage: ["global", "europe", "north-america", "middle-east", "asia", "africa"],
        categories: ["politics", "economy", "conflict", "diplomacy", "markets"],
        rssFeeds: ["https://feeds.reuters.com/reuters/worldNews"],
        googleFallbackQueries: ["Reuters world news"]
    },
    {
        id: "ap-news",
        name: "Associated Press",
        matchers: ["apnews.com"],
        country: "United States",
        region: "North America",
        tier: "top",
        influenceWeight: 1.3,
        reliabilityScore: 0.94,
        focus: "international",
        sourceType: "wire",
        language: "en",
        coverage: ["global", "north-america", "europe", "asia", "middle-east", "africa"],
        categories: ["politics", "conflict", "economy", "diplomacy"],
        rssFeeds: ["https://apnews.com/hub/world-news?output=rss"],
        googleFallbackQueries: ["Associated Press world news"]
    },

    // ===== UNITED KINGDOM =====
    {
        id: "bbc",
        name: "BBC",
        matchers: ["bbc.com", "bbc.co.uk"],
        country: "United Kingdom",
        region: "Europe",
        tier: "top",
        influenceWeight: 1.35,
        reliabilityScore: 0.93,
        focus: "international",
        sourceType: "public-broadcaster",
        language: "en",
        coverage: ["global", "europe", "asia", "middle-east", "africa", "uk"],
        categories: ["politics", "conflict", "diplomacy", "society"],
        rssFeeds: ["http://feeds.bbci.co.uk/news/world/rss.xml"],
        googleFallbackQueries: ["BBC world news"]
    },
    {
        id: "guardian",
        name: "The Guardian",
        matchers: ["theguardian.com"],
        country: "United Kingdom",
        region: "Europe",
        tier: "top",
        influenceWeight: 1.23,
        reliabilityScore: 0.9,
        focus: "international",
        sourceType: "newspaper",
        language: "en",
        coverage: ["global", "europe", "middle-east", "asia", "north-america", "uk"],
        categories: ["politics", "conflict", "climate", "economy"],
        rssFeeds: ["https://www.theguardian.com/world/rss"],
        googleFallbackQueries: ["The Guardian world news"]
    },
    {
        id: "sky-news",
        name: "Sky News",
        matchers: ["news.sky.com", "skynews.com"],
        country: "United Kingdom",
        region: "Europe",
        tier: "high",
        influenceWeight: 1.14,
        reliabilityScore: 0.86,
        focus: "international",
        sourceType: "tv",
        language: "en",
        coverage: ["global", "europe", "uk"],
        categories: ["politics", "conflict", "society"],
        rssFeeds: ["http://feeds.skynews.com/feeds/rss/world.xml"],
        googleFallbackQueries: ["Sky News world"]
    },
    {
        id: "financial-times",
        name: "Financial Times",
        matchers: ["ft.com"],
        country: "United Kingdom",
        region: "Europe",
        tier: "top",
        influenceWeight: 1.24,
        reliabilityScore: 0.92,
        focus: "business",
        sourceType: "newspaper",
        language: "en",
        coverage: ["global", "europe", "markets"],
        categories: ["economy", "markets", "geopolitics", "technology"],
        rssFeeds: [],
        googleFallbackQueries: ["Financial Times geopolitics", "Financial Times world economy"]
    },

    // ===== GERMANY =====
    {
        id: "dw",
        name: "DW",
        matchers: ["dw.com"],
        country: "Germany",
        region: "Europe",
        tier: "top",
        influenceWeight: 1.25,
        reliabilityScore: 0.91,
        focus: "international",
        sourceType: "public-broadcaster",
        language: "en",
        coverage: ["global", "europe", "asia", "middle-east", "germany"],
        categories: ["politics", "economy", "conflict", "diplomacy"],
        rssFeeds: ["https://rss.dw.com/xml/rss-en-world"],
        googleFallbackQueries: ["DW News world", "Deutsche Welle geopolitics"]
    },
    {
        id: "tagesschau",
        name: "Tagesschau",
        matchers: ["tagesschau.de"],
        country: "Germany",
        region: "Europe",
        tier: "top",
        influenceWeight: 1.22,
        reliabilityScore: 0.91,
        focus: "national",
        sourceType: "public-broadcaster",
        language: "de",
        coverage: ["germany", "europe", "global"],
        categories: ["politics", "conflict", "economy", "society"],
        rssFeeds: ["https://www.tagesschau.de/xml/rss2"],
        googleFallbackQueries: ["Tagesschau internationale Nachrichten"]
    },
    {
        id: "welt",
        name: "WELT",
        matchers: ["welt.de"],
        country: "Germany",
        region: "Europe",
        tier: "high",
        influenceWeight: 1.14,
        reliabilityScore: 0.84,
        focus: "national",
        sourceType: "newspaper",
        language: "de",
        coverage: ["germany", "europe", "global"],
        categories: ["politics", "economy", "security"],
        rssFeeds: ["https://www.welt.de/feeds/latest.rss"],
        googleFallbackQueries: ["WELT Nachrichten international"]
    },
    {
        id: "spiegel",
        name: "Der Spiegel",
        matchers: ["spiegel.de"],
        country: "Germany",
        region: "Europe",
        tier: "top",
        influenceWeight: 1.18,
        reliabilityScore: 0.88,
        focus: "national",
        sourceType: "magazine",
        language: "de",
        coverage: ["germany", "europe", "global"],
        categories: ["politics", "economy", "conflict", "society"],
        rssFeeds: ["https://www.spiegel.de/schlagzeilen/tops/index.rss"],
        googleFallbackQueries: ["Der Spiegel international Politik"]
    },
    {
        id: "zdf",
        name: "ZDF",
        matchers: ["zdf.de"],
        country: "Germany",
        region: "Europe",
        tier: "high",
        influenceWeight: 1.12,
        reliabilityScore: 0.88,
        focus: "national",
        sourceType: "public-broadcaster",
        language: "de",
        coverage: ["germany", "europe", "global"],
        categories: ["politics", "society", "conflict"],
        rssFeeds: [],
        googleFallbackQueries: ["ZDF heute international", "ZDF heute Politik"]
    },
    {
        id: "ard",
        name: "ARD",
        matchers: ["ard.de"],
        country: "Germany",
        region: "Europe",
        tier: "high",
        influenceWeight: 1.12,
        reliabilityScore: 0.88,
        focus: "national",
        sourceType: "public-broadcaster",
        language: "de",
        coverage: ["germany", "europe", "global"],
        categories: ["politics", "society", "conflict"],
        rssFeeds: [],
        googleFallbackQueries: ["ARD Nachrichten international"]
    },

    // ===== FRANCE =====
    {
        id: "france24",
        name: "France 24",
        matchers: ["france24.com"],
        country: "France",
        region: "Europe",
        tier: "top",
        influenceWeight: 1.22,
        reliabilityScore: 0.9,
        focus: "international",
        sourceType: "tv",
        language: "en",
        coverage: ["global", "europe", "africa", "middle-east", "france"],
        categories: ["politics", "conflict", "diplomacy"],
        rssFeeds: ["https://www.france24.com/en/rss"],
        googleFallbackQueries: ["France 24 world news"]
    },
    {
        id: "le-monde",
        name: "Le Monde",
        matchers: ["lemonde.fr"],
        country: "France",
        region: "Europe",
        tier: "top",
        influenceWeight: 1.2,
        reliabilityScore: 0.9,
        focus: "international",
        sourceType: "newspaper",
        language: "fr",
        coverage: ["france", "europe", "global", "africa"],
        categories: ["politics", "economy", "diplomacy"],
        rssFeeds: ["https://www.lemonde.fr/international/rss_full.xml"],
        googleFallbackQueries: ["Le Monde international"]
    },
    {
        id: "rfi",
        name: "RFI",
        matchers: ["rfi.fr"],
        country: "France",
        region: "Europe",
        tier: "high",
        influenceWeight: 1.12,
        reliabilityScore: 0.86,
        focus: "international",
        sourceType: "radio",
        language: "fr",
        coverage: ["global", "france", "africa", "europe"],
        categories: ["politics", "conflict", "diplomacy"],
        rssFeeds: ["https://www.rfi.fr/fr/rss"],
        googleFallbackQueries: ["RFI international"]
    },

    // ===== EUROPE REGIONAL =====
    {
        id: "euronews",
        name: "Euronews",
        matchers: ["euronews.com"],
        country: "France",
        region: "Europe",
        tier: "high",
        influenceWeight: 1.14,
        reliabilityScore: 0.86,
        focus: "international",
        sourceType: "tv",
        language: "en",
        coverage: ["global", "europe"],
        categories: ["politics", "economy", "conflict"],
        rssFeeds: ["https://www.euronews.com/rss?level=theme&name=news"],
        googleFallbackQueries: ["Euronews Europe"]
    },
    {
        id: "ansa",
        name: "ANSA",
        matchers: ["ansa.it"],
        country: "Italy",
        region: "Europe",
        tier: "high",
        influenceWeight: 1.08,
        reliabilityScore: 0.84,
        focus: "national",
        sourceType: "wire",
        language: "it",
        coverage: ["italy", "europe", "global"],
        categories: ["politics", "economy", "society"],
        rssFeeds: [],
        googleFallbackQueries: ["ANSA world news", "ANSA esteri"]
    },
    {
        id: "elpais",
        name: "El País",
        matchers: ["elpais.com"],
        country: "Spain",
        region: "Europe",
        tier: "high",
        influenceWeight: 1.1,
        reliabilityScore: 0.86,
        focus: "international",
        sourceType: "newspaper",
        language: "es",
        coverage: ["spain", "europe", "latin-america", "global"],
        categories: ["politics", "economy", "diplomacy"],
        rssFeeds: [],
        googleFallbackQueries: ["El País internacional"]
    },
    {
        id: "rtve",
        name: "RTVE",
        matchers: ["rtve.es"],
        country: "Spain",
        region: "Europe",
        tier: "high",
        influenceWeight: 1.08,
        reliabilityScore: 0.84,
        focus: "national",
        sourceType: "public-broadcaster",
        language: "es",
        coverage: ["spain", "europe", "global"],
        categories: ["politics", "society", "economy"],
        rssFeeds: [],
        googleFallbackQueries: ["RTVE internacional"]
    },
    {
        id: "nos",
        name: "NOS",
        matchers: ["nos.nl"],
        country: "Netherlands",
        region: "Europe",
        tier: "high",
        influenceWeight: 1.08,
        reliabilityScore: 0.86,
        focus: "national",
        sourceType: "public-broadcaster",
        language: "nl",
        coverage: ["netherlands", "europe", "global"],
        categories: ["politics", "society", "economy"],
        rssFeeds: [],
        googleFallbackQueries: ["NOS internationaal nieuws"]
    },
    {
        id: "svt",
        name: "SVT Nyheter",
        matchers: ["svt.se"],
        country: "Sweden",
        region: "Europe",
        tier: "high",
        influenceWeight: 1.06,
        reliabilityScore: 0.86,
        focus: "national",
        sourceType: "public-broadcaster",
        language: "sv",
        coverage: ["sweden", "europe", "global"],
        categories: ["politics", "society", "security"],
        rssFeeds: [],
        googleFallbackQueries: ["SVT Nyheter utrikes"]
    },
    {
        id: "yle",
        name: "Yle",
        matchers: ["yle.fi"],
        country: "Finland",
        region: "Europe",
        tier: "high",
        influenceWeight: 1.06,
        reliabilityScore: 0.86,
        focus: "national",
        sourceType: "public-broadcaster",
        language: "en",
        coverage: ["finland", "europe", "global"],
        categories: ["politics", "society", "security"],
        rssFeeds: [],
        googleFallbackQueries: ["Yle News international"]
    },
    {
        id: "nrk",
        name: "NRK",
        matchers: ["nrk.no"],
        country: "Norway",
        region: "Europe",
        tier: "high",
        influenceWeight: 1.06,
        reliabilityScore: 0.86,
        focus: "national",
        sourceType: "public-broadcaster",
        language: "no",
        coverage: ["norway", "europe", "global"],
        categories: ["politics", "society", "security"],
        rssFeeds: [],
        googleFallbackQueries: ["NRK utenriks"]
    },
    {
        id: "polsat",
        name: "Polsat News",
        matchers: ["polsatnews.pl"],
        country: "Poland",
        region: "Europe",
        tier: "standard",
        influenceWeight: 1.0,
        reliabilityScore: 0.78,
        focus: "national",
        sourceType: "tv",
        language: "pl",
        coverage: ["poland", "europe", "ukraine"],
        categories: ["politics", "security", "society"],
        rssFeeds: [],
        googleFallbackQueries: ["Polsat News świat"]
    },
    {
        id: "kyiv-independent",
        name: "The Kyiv Independent",
        matchers: ["kyivindependent.com"],
        country: "Ukraine",
        region: "Europe",
        tier: "high",
        influenceWeight: 1.12,
        reliabilityScore: 0.84,
        focus: "regional",
        sourceType: "digital",
        language: "en",
        coverage: ["ukraine", "europe", "russia", "security"],
        categories: ["conflict", "security", "politics", "diplomacy"],
        rssFeeds: [],
        googleFallbackQueries: ["The Kyiv Independent latest"]
    },

    // ===== INDIA =====
    {
        id: "ndtv",
        name: "NDTV",
        matchers: ["ndtv.com"],
        country: "India",
        region: "Asia",
        tier: "top",
        influenceWeight: 1.28,
        reliabilityScore: 0.88,
        focus: "national",
        sourceType: "tv",
        language: "en",
        coverage: ["india", "asia", "south-asia"],
        categories: ["politics", "economy", "security", "diplomacy"],
        rssFeeds: ["https://feeds.feedburner.com/ndtvnews-top-stories"],
        googleFallbackQueries: ["NDTV India news"]
    },
    {
        id: "times-of-india",
        name: "Times of India",
        matchers: ["timesofindia.indiatimes.com"],
        country: "India",
        region: "Asia",
        tier: "top",
        influenceWeight: 1.2,
        reliabilityScore: 0.84,
        focus: "national",
        sourceType: "newspaper",
        language: "en",
        coverage: ["india", "asia", "south-asia"],
        categories: ["politics", "economy", "security"],
        rssFeeds: ["https://timesofindia.indiatimes.com/rssfeedstopstories.cms"],
        googleFallbackQueries: ["Times of India national news"]
    },
    {
        id: "the-hindu",
        name: "The Hindu",
        matchers: ["thehindu.com"],
        country: "India",
        region: "Asia",
        tier: "top",
        influenceWeight: 1.18,
        reliabilityScore: 0.89,
        focus: "national",
        sourceType: "newspaper",
        language: "en",
        coverage: ["india", "asia", "global"],
        categories: ["politics", "economy", "diplomacy"],
        rssFeeds: [
            "https://www.thehindu.com/news/national/feeder/default.rss",
            "https://www.thehindu.com/news/international/feeder/default.rss"
        ],
        googleFallbackQueries: ["The Hindu international news"]
    },
    {
        id: "indian-express",
        name: "The Indian Express",
        matchers: ["indianexpress.com"],
        country: "India",
        region: "Asia",
        tier: "high",
        influenceWeight: 1.14,
        reliabilityScore: 0.86,
        focus: "national",
        sourceType: "newspaper",
        language: "en",
        coverage: ["india", "asia", "south-asia"],
        categories: ["politics", "economy", "security", "diplomacy"],
        rssFeeds: [],
        googleFallbackQueries: ["Indian Express world news", "Indian Express India security"]
    },
    {
        id: "economic-times",
        name: "The Economic Times",
        matchers: ["economictimes.indiatimes.com"],
        country: "India",
        region: "Asia",
        tier: "high",
        influenceWeight: 1.12,
        reliabilityScore: 0.84,
        focus: "business",
        sourceType: "newspaper",
        language: "en",
        coverage: ["india", "asia", "markets"],
        categories: ["economy", "markets", "technology", "policy"],
        rssFeeds: [],
        googleFallbackQueries: ["Economic Times India economy", "Economic Times geopolitics"]
    },
    {
        id: "hindustan-times",
        name: "Hindustan Times",
        matchers: ["hindustantimes.com"],
        country: "India",
        region: "Asia",
        tier: "high",
        influenceWeight: 1.1,
        reliabilityScore: 0.82,
        focus: "national",
        sourceType: "newspaper",
        language: "en",
        coverage: ["india", "asia"],
        categories: ["politics", "society", "economy"],
        rssFeeds: [],
        googleFallbackQueries: ["Hindustan Times world news"]
    },
    {
        id: "india-today",
        name: "India Today",
        matchers: ["indiatoday.in"],
        country: "India",
        region: "Asia",
        tier: "high",
        influenceWeight: 1.12,
        reliabilityScore: 0.82,
        focus: "national",
        sourceType: "tv",
        language: "en",
        coverage: ["india", "asia"],
        categories: ["politics", "security", "society"],
        rssFeeds: [],
        googleFallbackQueries: ["India Today latest news"]
    },
    {
        id: "republic-world",
        name: "Republic World",
        matchers: ["republicworld.com"],
        country: "India",
        region: "Asia",
        tier: "standard",
        influenceWeight: 1.03,
        reliabilityScore: 0.76,
        focus: "national",
        sourceType: "tv",
        language: "en",
        coverage: ["india", "asia"],
        categories: ["politics", "security", "society"],
        rssFeeds: [],
        googleFallbackQueries: ["Republic World India news"]
    },
    {
        id: "wion",
        name: "WION",
        matchers: ["wionews.com"],
        country: "India",
        region: "Asia",
        tier: "high",
        influenceWeight: 1.12,
        reliabilityScore: 0.8,
        focus: "international",
        sourceType: "tv",
        language: "en",
        coverage: ["global", "india", "asia", "middle-east"],
        categories: ["politics", "conflict", "diplomacy", "economy"],
        rssFeeds: [],
        googleFallbackQueries: ["WION world news"]
    },
    {
        id: "news18",
        name: "News18",
        matchers: ["news18.com"],
        country: "India",
        region: "Asia",
        tier: "standard",
        influenceWeight: 1.05,
        reliabilityScore: 0.78,
        focus: "national",
        sourceType: "tv",
        language: "en",
        coverage: ["india", "asia"],
        categories: ["politics", "society", "economy"],
        rssFeeds: [],
        googleFallbackQueries: ["News18 India news"]
    },
    {
        id: "zee-news",
        name: "Zee News",
        matchers: ["zeenews.india.com"],
        country: "India",
        region: "Asia",
        tier: "standard",
        influenceWeight: 1.02,
        reliabilityScore: 0.75,
        focus: "national",
        sourceType: "tv",
        language: "en",
        coverage: ["india", "asia"],
        categories: ["politics", "society", "security"],
        rssFeeds: [],
        googleFallbackQueries: ["Zee News India"]
    },

    // ===== ASIA PACIFIC =====
    {
        id: "scmp",
        name: "SCMP",
        matchers: ["scmp.com"],
        country: "Hong Kong",
        region: "Asia",
        tier: "top",
        influenceWeight: 1.22,
        reliabilityScore: 0.88,
        focus: "regional",
        sourceType: "newspaper",
        language: "en",
        coverage: ["asia", "china", "hong-kong", "taiwan"],
        categories: ["politics", "economy", "security", "diplomacy"],
        rssFeeds: ["https://www.scmp.com/rss/91/feed"],
        googleFallbackQueries: ["SCMP China news", "SCMP Asia news"]
    },
    {
        id: "channel-news-asia",
        name: "CNA",
        matchers: ["channelnewsasia.com"],
        country: "Singapore",
        region: "Asia",
        tier: "high",
        influenceWeight: 1.15,
        reliabilityScore: 0.87,
        focus: "regional",
        sourceType: "tv",
        language: "en",
        coverage: ["asia", "singapore", "china", "taiwan"],
        categories: ["politics", "economy", "security"],
        rssFeeds: ["https://www.channelnewsasia.com/rssfeeds/8395986"],
        googleFallbackQueries: ["CNA Asia news"]
    },
    {
        id: "nikkei",
        name: "Nikkei Asia",
        matchers: ["asia.nikkei.com", "nikkei.com"],
        country: "Japan",
        region: "Asia",
        tier: "top",
        influenceWeight: 1.18,
        reliabilityScore: 0.89,
        focus: "regional",
        sourceType: "newspaper",
        language: "en",
        coverage: ["asia", "japan", "china", "taiwan"],
        categories: ["economy", "markets", "technology", "security"],
        rssFeeds: ["https://asia.nikkei.com/rss/feed/nar"],
        googleFallbackQueries: ["Nikkei Asia geopolitics"]
    },
    {
        id: "japan-times",
        name: "The Japan Times",
        matchers: ["japantimes.co.jp"],
        country: "Japan",
        region: "Asia",
        tier: "high",
        influenceWeight: 1.1,
        reliabilityScore: 0.84,
        focus: "national",
        sourceType: "newspaper",
        language: "en",
        coverage: ["japan", "asia", "global"],
        categories: ["politics", "economy", "security"],
        rssFeeds: [],
        googleFallbackQueries: ["Japan Times politics"]
    },
    {
        id: "nhk",
        name: "NHK World",
        matchers: ["www3.nhk.or.jp", "nhk.or.jp"],
        country: "Japan",
        region: "Asia",
        tier: "top",
        influenceWeight: 1.14,
        reliabilityScore: 0.88,
        focus: "international",
        sourceType: "public-broadcaster",
        language: "en",
        coverage: ["japan", "asia", "global"],
        categories: ["politics", "society", "security"],
        rssFeeds: [],
        googleFallbackQueries: ["NHK World news"]
    },
    {
        id: "korea-herald",
        name: "The Korea Herald",
        matchers: ["koreaherald.com"],
        country: "South Korea",
        region: "Asia",
        tier: "high",
        influenceWeight: 1.08,
        reliabilityScore: 0.82,
        focus: "national",
        sourceType: "newspaper",
        language: "en",
        coverage: ["south-korea", "asia", "north-korea"],
        categories: ["politics", "security", "economy"],
        rssFeeds: [],
        googleFallbackQueries: ["Korea Herald security"]
    },
    {
        id: "yonhap",
        name: "Yonhap News Agency",
        matchers: ["yna.co.kr", "yonhapnews.co.kr"],
        country: "South Korea",
        region: "Asia",
        tier: "high",
        influenceWeight: 1.1,
        reliabilityScore: 0.84,
        focus: "national",
        sourceType: "wire",
        language: "en",
        coverage: ["south-korea", "north-korea", "asia"],
        categories: ["politics", "security", "diplomacy"],
        rssFeeds: [],
        googleFallbackQueries: ["Yonhap North Korea"]
    },
    {
        id: "taipei-times",
        name: "Taipei Times",
        matchers: ["taipeitimes.com"],
        country: "Taiwan",
        region: "Asia",
        tier: "high",
        influenceWeight: 1.08,
        reliabilityScore: 0.82,
        focus: "national",
        sourceType: "newspaper",
        language: "en",
        coverage: ["taiwan", "china", "asia", "semiconductors"],
        categories: ["politics", "security", "technology", "economy"],
        rssFeeds: [],
        googleFallbackQueries: ["Taipei Times China Taiwan"]
    },
    {
        id: "abc-australia",
        name: "ABC News Australia",
        matchers: ["abc.net.au"],
        country: "Australia",
        region: "Oceania",
        tier: "top",
        influenceWeight: 1.12,
        reliabilityScore: 0.88,
        focus: "national",
        sourceType: "public-broadcaster",
        language: "en",
        coverage: ["australia", "oceania", "asia-pacific", "global"],
        categories: ["politics", "security", "society"],
        rssFeeds: [],
        googleFallbackQueries: ["ABC News Australia world"]
    },

    // ===== MIDDLE EAST =====
    {
        id: "al-jazeera",
        name: "Al Jazeera",
        matchers: ["aljazeera.com"],
        country: "Qatar",
        region: "Middle East",
        tier: "top",
        influenceWeight: 1.35,
        reliabilityScore: 0.91,
        focus: "international",
        sourceType: "tv",
        language: "en",
        coverage: ["global", "middle-east", "asia", "africa"],
        categories: ["politics", "conflict", "diplomacy", "humanitarian"],
        rssFeeds: ["https://www.aljazeera.com/xml/rss/all.xml"],
        googleFallbackQueries: ["Al Jazeera Middle East"]
    },
    {
        id: "arab-news",
        name: "Arab News",
        matchers: ["arabnews.com"],
        country: "Saudi Arabia",
        region: "Middle East",
        tier: "high",
        influenceWeight: 1.12,
        reliabilityScore: 0.84,
        focus: "regional",
        sourceType: "newspaper",
        language: "en",
        coverage: ["middle-east", "saudi-arabia", "iran", "israel"],
        categories: ["politics", "conflict", "energy", "diplomacy"],
        rssFeeds: ["https://www.arabnews.com/rss.xml"],
        googleFallbackQueries: ["Arab News Middle East"]
    },
    {
        id: "times-of-israel",
        name: "Times of Israel",
        matchers: ["timesofisrael.com"],
        country: "Israel",
        region: "Middle East",
        tier: "high",
        influenceWeight: 1.12,
        reliabilityScore: 0.84,
        focus: "national",
        sourceType: "newspaper",
        language: "en",
        coverage: ["middle-east", "israel", "iran"],
        categories: ["politics", "conflict", "security", "diplomacy"],
        rssFeeds: ["https://www.timesofisrael.com/feed/"],
        googleFallbackQueries: ["Times of Israel Iran"]
    },
    {
        id: "haaretz",
        name: "Haaretz",
        matchers: ["haaretz.com"],
        country: "Israel",
        region: "Middle East",
        tier: "high",
        influenceWeight: 1.1,
        reliabilityScore: 0.84,
        focus: "national",
        sourceType: "newspaper",
        language: "en",
        coverage: ["israel", "middle-east", "iran"],
        categories: ["politics", "conflict", "security"],
        rssFeeds: [],
        googleFallbackQueries: ["Haaretz Middle East"]
    },
    {
        id: "tehran-times",
        name: "Tehran Times",
        matchers: ["tehrantimes.com"],
        country: "Iran",
        region: "Middle East",
        tier: "standard",
        influenceWeight: 0.95,
        reliabilityScore: 0.7,
        focus: "national",
        sourceType: "newspaper",
        language: "en",
        coverage: ["iran", "middle-east", "israel"],
        categories: ["politics", "energy", "conflict"],
        rssFeeds: [],
        googleFallbackQueries: ["Tehran Times international"]
    },

    // ===== NORTH AMERICA =====
    {
        id: "cnn",
        name: "CNN",
        matchers: ["cnn.com"],
        country: "United States",
        region: "North America",
        tier: "top",
        influenceWeight: 1.3,
        reliabilityScore: 0.9,
        focus: "international",
        sourceType: "tv",
        language: "en",
        coverage: ["global", "north-america", "middle-east", "asia", "europe"],
        categories: ["politics", "conflict", "diplomacy", "security"],
        rssFeeds: ["http://rss.cnn.com/rss/edition_world.rss"],
        googleFallbackQueries: ["CNN world news"]
    },
    {
        id: "npr",
        name: "NPR",
        matchers: ["npr.org"],
        country: "United States",
        region: "North America",
        tier: "top",
        influenceWeight: 1.14,
        reliabilityScore: 0.89,
        focus: "international",
        sourceType: "radio",
        language: "en",
        coverage: ["global", "united-states", "north-america"],
        categories: ["politics", "society", "diplomacy"],
        rssFeeds: ["https://feeds.npr.org/1004/rss.xml"],
        googleFallbackQueries: ["NPR world"]
    },
    {
        id: "pbs",
        name: "PBS NewsHour",
        matchers: ["pbs.org"],
        country: "United States",
        region: "North America",
        tier: "high",
        influenceWeight: 1.1,
        reliabilityScore: 0.88,
        focus: "international",
        sourceType: "public-broadcaster",
        language: "en",
        coverage: ["global", "united-states"],
        categories: ["politics", "society", "diplomacy"],
        rssFeeds: [],
        googleFallbackQueries: ["PBS NewsHour world"]
    },
    {
        id: "cbc",
        name: "CBC News",
        matchers: ["cbc.ca"],
        country: "Canada",
        region: "North America",
        tier: "top",
        influenceWeight: 1.12,
        reliabilityScore: 0.88,
        focus: "national",
        sourceType: "public-broadcaster",
        language: "en",
        coverage: ["canada", "north-america", "global"],
        categories: ["politics", "society", "economy"],
        rssFeeds: [],
        googleFallbackQueries: ["CBC world news"]
    },

    // ===== LATIN AMERICA =====
    {
        id: "folha",
        name: "Folha de S.Paulo",
        matchers: ["folha.uol.com.br"],
        country: "Brazil",
        region: "South America",
        tier: "high",
        influenceWeight: 1.08,
        reliabilityScore: 0.82,
        focus: "national",
        sourceType: "newspaper",
        language: "pt",
        coverage: ["brazil", "south-america", "global"],
        categories: ["politics", "economy", "society"],
        rssFeeds: [],
        googleFallbackQueries: ["Folha mundo"]
    },
    {
        id: "globo",
        name: "G1 / Globo",
        matchers: ["g1.globo.com", "globo.com"],
        country: "Brazil",
        region: "South America",
        tier: "high",
        influenceWeight: 1.1,
        reliabilityScore: 0.82,
        focus: "national",
        sourceType: "tv",
        language: "pt",
        coverage: ["brazil", "south-america", "global"],
        categories: ["politics", "economy", "society"],
        rssFeeds: [],
        googleFallbackQueries: ["G1 mundo"]
    },
    {
        id: "clarin",
        name: "Clarín",
        matchers: ["clarin.com"],
        country: "Argentina",
        region: "South America",
        tier: "standard",
        influenceWeight: 1.0,
        reliabilityScore: 0.78,
        focus: "national",
        sourceType: "newspaper",
        language: "es",
        coverage: ["argentina", "south-america", "global"],
        categories: ["politics", "economy", "society"],
        rssFeeds: [],
        googleFallbackQueries: ["Clarín mundo"]
    },

    // ===== AFRICA =====
    {
        id: "allafrica",
        name: "AllAfrica",
        matchers: ["allafrica.com"],
        country: "South Africa",
        region: "Africa",
        tier: "high",
        influenceWeight: 1.1,
        reliabilityScore: 0.8,
        focus: "regional",
        sourceType: "digital",
        language: "en",
        coverage: ["africa", "global"],
        categories: ["politics", "economy", "conflict", "society"],
        rssFeeds: [],
        googleFallbackQueries: ["AllAfrica latest"]
    },
    {
        id: "news24",
        name: "News24",
        matchers: ["news24.com"],
        country: "South Africa",
        region: "Africa",
        tier: "high",
        influenceWeight: 1.08,
        reliabilityScore: 0.8,
        focus: "national",
        sourceType: "digital",
        language: "en",
        coverage: ["south-africa", "africa"],
        categories: ["politics", "economy", "society"],
        rssFeeds: [],
        googleFallbackQueries: ["News24 Africa"]
    },
    {
        id: "daily-nation",
        name: "Daily Nation",
        matchers: ["nation.africa"],
        country: "Kenya",
        region: "Africa",
        tier: "high",
        influenceWeight: 1.06,
        reliabilityScore: 0.8,
        focus: "national",
        sourceType: "newspaper",
        language: "en",
        coverage: ["kenya", "east-africa", "africa"],
        categories: ["politics", "economy", "security"],
        rssFeeds: [],
        googleFallbackQueries: ["Daily Nation Kenya world"]
    }
];

const COUNTRY_TO_REGION = {
    argentina: "South America",
    australia: "Oceania",
    austria: "Europe",
    belgium: "Europe",
    brazil: "South America",
    britain: "Europe",
    canada: "North America",
    china: "Asia",
    finland: "Europe",
    france: "Europe",
    germany: "Europe",
    "hong kong": "Asia",
    india: "Asia",
    iran: "Middle East",
    israel: "Middle East",
    italy: "Europe",
    japan: "Asia",
    kenya: "Africa",
    netherlands: "Europe",
    norway: "Europe",
    poland: "Europe",
    qatar: "Middle East",
    "saudi arabia": "Middle East",
    singapore: "Asia",
    "south africa": "Africa",
    "south korea": "Asia",
    spain: "Europe",
    sweden: "Europe",
    taiwan: "Asia",
    uk: "Europe",
    ukraine: "Europe",
    "united kingdom": "Europe",
    "united states": "North America",
    us: "North America",
    usa: "North America"
};

function normalizeKey(value = "") {
    return String(value).trim().toLowerCase();
}

function resolveRegionFromCountry(country = "") {
    return COUNTRY_TO_REGION[normalizeKey(country)] || "";
}

module.exports = {
    SOURCE_REGISTRY,
    COUNTRY_TO_REGION,
    normalizeKey,
    resolveRegionFromCountry
};