name: Deploy Geo-Sentinel React Frontend to S3

on:
push:
branches:
- main

jobs:
deploy:
name: Build and Deploy React Frontend
runs-on: ubuntu-latest

```
permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: eu-central-1
  S3_BUCKET_NAME: geo-sentinel-web-frontend-632150488936

steps:
  - name: Checkout repository
    uses: actions/checkout@v4

  - name: Setup Node
    uses: actions/setup-node@v4
    with:
      node-version: 20

  - name: Install dependencies
    working-directory: frontend-react
    run: npm ci

  - name: Build React app
    working-directory: frontend-react
    run: npm run build

  - name: Configure AWS credentials
    uses: aws-actions/configure-aws-credentials@v4
    with:
      role-to-assume: arn:aws:iam::632150488936:role/GeoSentinelGitHubDeployRole
      aws-region: ${{ env.AWS_REGION }}

  - name: Deploy React build to S3
    run: |
      aws s3 sync frontend-react/dist/ s3://${{ env.S3_BUCKET_NAME }} --delete
```
